name: Tests
on: [push, pull_request]
jobs:
  test-node:
    matrix:
      node-version: [14, 16, 18]
      fail-fast: false
    name: Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node-version }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make node_modules
      - name: Run checks
        run: make check
      - name: Run tests
        run: make ci-test
